<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <AssemblyName>KalashnikovEnhancedModding</AssemblyName><Version>$(ModVersion)</Version>
    <Product>$(ModName)</Product>
    <Authors>$(ModAuthor)</Authors>
    <RepositoryUrl>$(ModSourceUrl)</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="ModVersion" Value="$(ModVersion)" />
    <AssemblyMetadata Include="ModGuid" Value="$(ModGuid)" />
    <AssemblyMetadata Include="ModName" Value="$(ModName)" />
    <AssemblyMetadata Include="ModAuthor" Value="$(ModAuthor)" />
    <AssemblyMetadata Include="ModSourceUrl" Value="$(ModSourceUrl)" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Reference Include="0Harmony"><HintPath>$(SptRoot)/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="SPTarkov.Server.Core"><HintPath>$(SptRoot)/SPTarkov.Server.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="SPTarkov.Common"><HintPath>$(SptRoot)/SPTarkov.Common.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="SPTarkov.DI"><HintPath>$(SptRoot)/SPTarkov.DI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="SemanticVersioning"><HintPath>$(SptRoot)/SemanticVersioning.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="WTT-ServerCommonLib"><HintPath>$(CommonLibPath)</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup><Content Include="../ServerModFiles/db/**/*.json" Link="db/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
</Project>
